// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Moment = require("moment");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactDatepicker = require("react-datepicker");

var moment = Moment;

function make(selected, onChange, children) {
  var tmp = { };
  if (selected) {
    tmp.selected = selected[0];
  }
  if (onChange) {
    tmp.onChange = onChange[0];
  }
  return ReasonReact.wrapJsForReason(ReactDatepicker.default, tmp, children);
}

exports.moment = moment;
exports.make = make;
/* moment Not a pure module */
